export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE'

export const PRODUCT_APPLY_FILTER = 'PRODUCT_APPLY_FILTER'
export const PRODUCT_CLEAR_FILTER = 'PRODUCT_CLEAR_FILTER'

export const PRODUCT_PAGE_LENGTH = 8